# Generated by Django 3.2.8 on 2022-10-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_delete_companyadvocates'),
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advocates', to='companies.company'),
        ),
    ]
